spring:
  application:
    name: primer-servicio
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: a
    password: a
    url: "jdbc:mysql://localhost:3306/sistema_prueba"
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop